create table public.collisions
(
date date,
	time time,
	borough varchar,
	zipcode varchar,
	latitude double precision,
	longitude double precision,
	location geometry,
	on_street varchar,
	cross_street varchar,
	off_street varchar,
	inj int,
	kill int, 
	ped_inj int,
	ped_kill int,
	cyc_inj int,
	cyc_kill int,
	mot_inj int,
	mot_kill int,
	cfveh1 varchar,
	cfveh2 varchar,
	cfveh3 varchar,
	cfveh4 varchar,
	cfveh5 varchar,
	uniquekey bigint,
	vehcode1 varchar,
	vehcode2 varchar, 
	vehcode3 varchar,
	vehcode4 varchar,
	vehcode5 varchar
)